import io
import json
import zipfile
import re
from dataclasses import asdict
from typing import Any, Optional
from .deg_export_spec import DegExportPayload
from .deg_handoff_builder import build_deg_handoff_payload

def build_deg_export_bundle_filename(payload: DegExportPayload) -> str:
    """
    Generate a sanitized filename for the export bundle.
    """
    raw_name = f"deg_bundle_{payload.summary.group_a}_vs_{payload.summary.group_b}"
    # Sanitize: replace non-alphanumeric (except underscores/hyphens) with underscore
    sanitized = re.sub(r"[^a-zA-Z0-9_\-]", "_", raw_name)
    return f"{sanitized}.zip"

def build_deg_export_bundle(payload: DegExportPayload, bundle_filename: Optional[str] = None) -> bytes:
    """
    Assemble a ZIP archive containing all DEG export components in-memory.
    """
    if bundle_filename is None:
        bundle_filename = build_deg_export_bundle_filename(payload)

    # Generate handoff contract for inclusion
    handoff_payload = build_deg_handoff_payload(payload, bundle_filename)

    buf = io.BytesIO()
    
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # 1. Result Table (CSV)
        zf.writestr("deg_results.csv", payload.result_table.to_csv(index=False))
        
        # 2. Summaries (JSON)
        zf.writestr(
            "comparison_summary.json",
            json.dumps(payload.summary.to_dict(), indent=2, ensure_ascii=False)
        )
        zf.writestr(
            "run_metadata.json",
            json.dumps(payload.metadata.to_dict(), indent=2, ensure_ascii=False)
        )
        zf.writestr(
            "summary_metrics.json",
            json.dumps(asdict(payload.summary_metrics), indent=2, ensure_ascii=False)
        )

        # 3. Handoff Contract (JSON)
        zf.writestr(
            "handoff_contract.json",
            json.dumps(handoff_payload.to_dict(), indent=2, ensure_ascii=False)
        )
        
        # 4. Report Summary (Markdown)
        report_text = build_deg_report_summary_md(payload)
        zf.writestr("report_summary.md", report_text)
        
    return buf.getvalue()

def build_deg_report_summary_md(payload: DegExportPayload) -> str:
    """
    Internal helper to build a human-readable report summary.
    """
    s = payload.summary
    m = payload.metadata
    metrics = payload.summary_metrics
    
    lines = [
        f"# DEG Analysis Report Summary",
        f"",
        f"## 1. Comparison Overview",
        f"- **Label**: {s.comparison_label}",
        f"- **Column**: {s.comparison_column}",
        f"- **Group A (Case)**: {s.group_a} (n={s.sample_count_group_a})",
        f"- **Group B (Control)**: {s.group_b} (n={s.sample_count_group_b})",
        f"",
        f"## 2. Analysis Parameters",
        f"- **Matrix Kind**: {m.matrix_kind}",
        f"- **Log2(P+1) Transformation**: {m.log2p1}",
        f"- **Exclude Flag Samples**: {m.use_exclude}",
        f"- **Min Non-zero Samples**: {m.min_feature_nonzero_samples}",
        f"- **Min Feature Mean**: {m.min_feature_mean}",
        f"- **P-adj Threshold**: {m.padj_threshold}",
        f"- **|Log2FC| Threshold**: {m.abs_log2_fc_threshold}",
        f"",
        f"## 3. Results Summary",
        f"- **Features Tested**: {metrics.n_features_tested}",
        f"- **Significantly Up Case**: {metrics.n_sig_up}",
        f"- **Significantly Down Case**: {metrics.n_sig_down}",
        f"- **Max |Log2FC|**: {metrics.max_abs_log2_fc:.4f}",
        f"",
        f"---",
        f"Generated by iwa-rnaseq-reporter."
    ]
    return "\n".join(lines)
