import pytest
import os
import zipfile
import io
from pathlib import Path
from tempfile import TemporaryDirectory
from iwa_rnaseq_reporter.app.comparator_consensus import (
    ComparatorConsensusContext,
    ConsensusDecisionSpec,
    ConsensusEvidenceProfileSpec,
    ComparatorConsensusSummarySpec
)
from iwa_rnaseq_reporter.app.comparator_consensus_export_builder import (
    build_consensus_export_payload,
    build_consensus_export_bundle,
    build_consensus_run_id
)
from iwa_rnaseq_reporter.app.comparator_consensus_handoff_builder import (
    build_consensus_handoff_payload,
    serialize_handoff_contract
)
from iwa_rnaseq_reporter.app.comparator_consensus_import_builder import read_consensus_bundle

def test_consensus_export_import_roundtrip():
    with TemporaryDirectory() as tmpdir:
        root = Path(tmpdir)
        
        # 1. Setup Mock Consensus Data
        dec = ConsensusDecisionSpec("cid1", "consensus", "L1", "Label 1", ())
        prof = ConsensusEvidenceProfileSpec("cid1", None, (), (), (), 0.5, False, False)
        summary = ComparatorConsensusSummarySpec(1, 1, 0, 0, 0, True)
        
        # Use a mock for ranking_context as it's not direct output
        from unittest.mock import MagicMock
        ctx = ComparatorConsensusContext(
            ranking_context=MagicMock(),
            decisions=(dec,),
            evidence_profiles=(prof,),
            issues=(),
            summary=summary
        )
        
        # 2. Export
        run_id = "roundtrip_run"
        # v0.19.2a: Unify timestamp during orchestration
        import datetime
        gen_at = datetime.datetime.now(datetime.timezone.utc).isoformat()
        
        payload = build_consensus_export_payload(ctx, run_id, generated_at=gen_at)
        handoff = build_consensus_handoff_payload(ctx, payload, "bundle.zip", generated_at=gen_at)
        handoff_json = serialize_handoff_contract(handoff)
        
        # Build the bundle first
        bundle_bytes = build_consensus_export_bundle(payload, handoff_json)
        
        # 3. Simulate Bundle Extraction
        # We MUST extract the bytes generated by build_consensus_export_bundle
        with zipfile.ZipFile(io.BytesIO(bundle_bytes)) as zf:
            zf.extractall(root)
            
        # 4. Import
        import_ctx = read_consensus_bundle(root, load_tables=True)
        
        # 5. Compare manifest identity
        assert import_ctx.manifest["consensus_run_id"] == run_id
        assert import_ctx.manifest["schema_name"] == "ConsensusExportManifest"
        assert import_ctx.manifest["generated_at"] == gen_at
        
        # 6. Compare handoff parity
        assert import_ctx.handoff_contract["consensus_run_id"] == run_id
        assert import_ctx.handoff_contract["generated_at"] == gen_at
        assert import_ctx.handoff_contract["generated_at"] == import_ctx.manifest["generated_at"]
        
        # 7. Compare Data Loading (v0.19.2a)
        assert import_ctx.summary_markdown is not None
        # The real summary starts with this header (v0.18.4 style)
        assert "RNA-Seq Consensus Report Summary" in import_ctx.summary_markdown
        assert import_ctx.results_table is not None
        assert len(import_ctx.results_table) == 1
        # CSV column names in real export include 'comparison_id'
        assert import_ctx.results_table.iloc[0]["comparison_id"] == "cid1"
